---

- name: Assert ssmtp_group and ssmtp_user Are Used Together
  assert:
    that:
      - ssmtp_group is not none
      - ssmtp_user is not none
  when: ssmtp_group is not none
          or
        ssmtp_user is not none

- name: Assert user/pass are provided when using SMTP authentication
  assert:
    that:
      - ssmtp_mailserver_username is not none
      - ssmtp_mailserver_password is not none
  when:
    - ssmtp_auth | bool
