---

- name: Ensure SSMTP Configuration
  template:
    dest: "/etc/ssmtp/{{ item }}"
    group: "{{ ssmtp_group }}"
    mode: 0o600
    owner: "{{ ssmtp_user }}"
    src: "{{ item }}.j2"
  loop:
    - revaliases
    - ssmtp.conf
