---

- name: Install SSMTP
  apt:
    name: ssmtp

- name: >-
    Restrict SSMTP Usage to User {{ ssmtp_user }}
    and Group {{ ssmtp_group }}
  file:
    dest: /usr/sbin/ssmtp
    owner: "{{ ssmtp_user }}"
    group: "{{ ssmtp_group }}"
    mode: 0o770
  when:
    - ssmtp_group is not none
    - ssmtp_user is not none
    - ssmtp_restrict | bool

- name: >-
    Allow access to SSMTP Configuration dir to User {{ ssmtp_user }}
    and Group {{ ssmtp_group }}
  file:
    dest: /etc/ssmtp
    group: "{{ ssmtp_group }}"
    mode: 0o700
    owner: "{{ ssmtp_user }}"
    state: directory
  when:
    - ssmtp_group is not none
    - ssmtp_user is not none
    - ssmtp_restrict | bool
